### ISSUE TITLE
just tried your python script - borders still there

### ISSUE THREAD

**Issue by jbiddulph** [loglux/remove_black_borders#1]
hi, I am running python 3 with pip3 commands, I added my images to book folder and rand the line: python3 remove_black_borders.py
Although my borders are white, I change dteh threshold and the naming etc and still I have border in the cropped_book folder, nothing is cropped?!

**Comment by loglux** [comment]
Could you please provide an example image from your "book" folder that you're experiencing issues with?

**Comment by jbiddulph** [comment]
This image attached has a white border I would like cropped

Thanks

john

**Comment by loglux** [comment]
I don't see the attachment.

**Comment by loglux** [comment]
#2

**Comment by loglux** [comment]
The script is designed to remove black borders and performs this task well for me. Moreover, it completes the task rapidly due to the use of `ThreadPoolExecutor`, which enables the parallel processing of multiple images.

I will be closing both the original issue and its duplicate because of the lack of responses and the absence of an example of the white borders. The script was not originally intended to handle white borders. However, I am open to revisiting this issue in the future if a relevant example that needs processing is provided. For the moment, the script's purpose is to remove black borders, and white borders do not fall within its scope.
